CREATE TABLE `shop_locations` (
	`id` text PRIMARY KEY NOT NULL,
	`location` text NOT NULL UNIQUE,
	`item` text NOT NULL
);

INSERT INTO `shop_locations` (`id`, `location`, `item`) VALUES
('shop-w1-a', 'W1-A', 'Gear Motors'),
('shop-w2-a', 'W2-A', 'Network Switch'),
('shop-w3-a', 'W3-A', 'Wire Loom'),
('shop-w4-a', 'W4-A', 'Empty'),
('shop-w5-a', 'W5-A', 'Tape'),
('shop-w6-a', 'W6-A', 'Empty'),
('shop-w7-a', 'W7-A', 'Churro Locker'),
('shop-w8-a', 'W8-A', 'Dell Docks'),
('shop-w9-a', 'W9-A', 'Oversized HTD'),
('shop-w10-a', 'W10-A', 'Odd Bolts'),
('shop-w11-a', 'W11-A', 'Zip Square, & Nylon HW'),
('shop-w12-a', 'W12-A', 'Tormach'),
('shop-w1-b', 'W1-B', 'Mini-CIM 7 Bag'),
('shop-w2-b', 'W2-B', 'Empty'),
('shop-w3-b', 'W3-B', 'Igus'),
('shop-w4-b', 'W4-B', 'Mac Mini & Speakers'),
('shop-w5-b', 'W5-B', 'Tape, Gaffers'),
('shop-w6-b', 'W6-B', 'Empty'),
('shop-w7-b', 'W7-B', '1/4-20 Overflow'),
('shop-w8-b', 'W8-B', 'Empty'),
('shop-w9-b', 'W9-B', '5/16 Bolts, Dust Collector'),
('shop-w10-b', 'W10-B', 'Empty'),
('shop-w11-b', 'W11-B', 'Nylon HW'),
('shop-w12-b', 'W12-B', 'Prusa (Combine with W4-D)'),
('shop-w1-c', 'W1-C', 'CIM Motors'),
('shop-w2-c', 'W2-C', 'Empty'),
('shop-w3-c', 'W3-C', 'Swerve'),
('shop-w4-c', 'W4-C', 'Old, Not Forgotten'),
('shop-w5-c', 'W5-C', 'Grinding Wheels'),
('shop-w6-c', 'W6-C', '80/20'),
('shop-w7-c', 'W7-C', 'Rivet Overflow'),
('shop-w8-c', 'W8-C', 'Odd Hardware'),
('shop-w9-c', 'W9-C', 'Empty'),
('shop-w10-c', 'W10-C', 'Vernier Scale'),
('shop-w11-c', 'W11-C', 'Odd Hardware'),
('shop-w12-c', 'W12-C', 'Lathe Legs (Combine with Tormach?)'),
('shop-w1-d', 'W1-D', '775 Motors'),
('shop-w2-d', 'W2-D', 'Short Ethernet'),
('shop-w3-d', 'W3-D', 'Empty'),
('shop-w4-d', 'W4-D', 'Prusa'),
('shop-w5-d', 'W5-D', 'Grease'),
('shop-w6-d', 'W6-D', 'Bags'),
('shop-w7-d', 'W7-D', '#10-32 Overflow'),
('shop-w8-d', 'W8-D', 'Electronics Overflow'),
('shop-w9-d', 'W9-D', 'Empty'),
('shop-w10-d', 'W10-D', 'Empty'),
('shop-w11-d', 'W11-D', 'HW Nylon'),
('shop-w12-d', 'W12-D', 'Plywood Spacers'),
('shop-w1-e', 'W1-E', 'Gear Motors'),
('shop-w2-e', 'W2-E', 'Port Savers'),
('shop-w3-e', 'W3-E', 'Wire Management'),
('shop-w4-e', 'W4-E', 'Backpack'),
('shop-w5-e', 'W5-E', 'Glue'),
('shop-w6-e', 'W6-E', 'Decorations'),
('shop-w7-e', 'W7-E', '#8-32 Overflow'),
('shop-w8-e', 'W8-E', 'Empty'),
('shop-w9-e', 'W9-E', 'Spacer Overflow'),
('shop-w10-e', 'W10-E', 'Empty'),
('shop-w11-e', 'W11-E', 'Grommet'),
('shop-w12-e', 'W12-E', 'Empty'),
('shop-w1-f', 'W1-F', 'Gear Boxes'),
('shop-w2-f', 'W2-F', 'Empty'),
('shop-w3-f', 'W3-F', 'Brushes'),
('shop-w4-f', 'W4-F', 'Cinder Blocks'),
('shop-w5-f', 'W5-F', 'Office, Label Tape, Zip Squares'),
('shop-w6-f', 'W6-F', 'Trays'),
('shop-w7-f', 'W7-F', 'Misc HW Overflow'),
('shop-w8-f', 'W8-F', 'Old Hardware'),
('shop-w9-f', 'W9-F', 'Bearing Overflow'),
('shop-w10-f', 'W10-F', 'Empty'),
('shop-w11-f', 'W11-F', 'Hardware'),
('shop-w12-f', 'W12-F', '4-Jaw Chuck');
